### ISSUE TITLE
Brightness math

### ISSUE THREAD

**Issue by jjensn** [mxtra/pyyeelight#5]
Hey I was looking through this code -- I wanted to ask you about brightness.

It's very possible I don't understand what HA is sending to the python module, but I thought HA measured brightness from 1-255 (https://home-assistant.io/developers/platform_example_light/)

http://www.thehelloworldprogram.com/python/python-operators-order-precedence/

So, if we look at the math function:

`self.operate_on_bulb('set_bright', str(round(self.brightness
                             / 255 * 100)) + ',"smooth",'
                             + str(transtime))`

Doesn't this give us:

`[brightness]/(255*100)` ?

I'm pretty terrible at math, so lmk if I'm wrong (I'm sure I am)

**Comment by mxtra** [comment]
As far as I know, multiplication and division are of equal precedence. So this shouldn't be a problem here as long as Python does respect the convention.
